### ISSUE TITLE
Error when running `GPU Value Function Iteration under Uncertainty.ipynb` notebook

### ISSUE THREAD

**Issue by lagefreitas** [giob1994/OpenCL-VFI-in-Julia#1]
hi @giob1994 , please find it in the following screenshots. I tested it by using Julia 0.6.3 in a MacOS, local IJulia installation. BTW, do you know if it runs seamlessly at JuliaBox?

Thanks!

![screen shot 2018-08-03 at 09 21 06](https://user-images.githubusercontent.com/5229514/43645160-7ccf52d8-9707-11e8-9264-13c52f32ecbc.png)
![screen shot 2018-08-03 at 10 15 32](https://user-images.githubusercontent.com/5229514/43645162-7cf2f300-9707-11e8-847c-fe2b9e183bd1.png)

**Comment by giob1994** [comment]
Hey! So I have checked this notebook on my computer (MacOS 10.13, Julia 0.6.2, Jupyter 1.0.0) and everything works well!

Potential causes of the errors:

1. I am currently using Jupiter Lab (v0.33.4), so some pieces of the notebook may not be perfectly interchangeable with standard Jupiter Notebooks (maybe)...
2. GPUArrays.jl and CLArrays.jl not installed (error "CLArrays not defined");

Let me know if using Lab and checking the installation of these two Julia packages helps... 

Anyhow, I'll push an update to this notebook of my last run... Maybe there was some error in the notebook encoding, too?

**Comment by lagefreitas** [comment]
It worked, thanks! 

Indeed, I didn't have installed GPUArrays and CLArrays packages, sorry for not having read this note: "The OpenCL.jl, GPUArrays.jl and CLArrays.jl packages are required to run the GPU code."
